### ISSUE TITLE
library not available in processing 3.0 contributed library manager

### ISSUE THREAD

**Issue by nosarious** [gicentre/handy#7]
I see that it was available as an easy-install in processing 2.0, according to this page: https://www.gicentre.net/handy/

but it is not available in processing 3.0. (the gicentreUtils library is available, however)

I see this code was updated five months ago, but I have not tested it in processing 3 yet.

**Comment by q2dg** [comment]
Well...https://github.com/gicentre/handy/issues/5

**Comment by barefootliam** [comment]
update: i installed the gicentreUtils library and also the handy.zip from the Web page rather than github, and it worked. Maybe slightly more docs would help.

**Comment by C-Kenny** [comment]
Still unable to install in Processing 3, using the library manager.

To use the Handy library (which is amazing btw), I unzip'd Handy to `~/sketchbook/libraries`.

**Comment by q2dg** [comment]
Maybe it's time to a fork and having this fork integrated into library manager due to lack of interest here

**Comment by jwoLondon** [comment]
Apologies for not doing this sooner. I will endeavour to get this integrated with the Processing library manager in the next few days.

**Comment by MichaelMifsudSweeney** [comment]
Any updates here? trying to get this working in 3.5.2 

@jwoLondon Thank you so much for looking into this!

**Comment by jwoLondon** [comment]
The request to add Handy to the library manager is with the Processing Foundation so hopefully it will be available imminently. I'll report back here (and close this issue) as soon as it is up.

**Comment by jwoLondon** [comment]
It took a while for the Processing Foundation to approve, but handy is now available via the library manager.
