### ISSUE TITLE
Can't get SVG export to work with HandyRenderer

### ISSUE THREAD

**Issue by Ohmarinus** [gicentre/handy#8]
Maybe not a bug, not sure, but I'm using processing.svg to create svg's with beginRecord();, vertex(); and endRecord(); to create SVG's. However the geometry created within HandyRenderer does not show up. The non HandyRenderer geometry does show up.

Is there a special function in HandyRenderer to create SVG export?

**Comment by jwoLondon** [comment]
You should be able to render to PDF with Handy. It certainly works if you set the renderer to PDF:

```java
import org.gicentre.handy.*;
import processing.pdf.*;

HandyRenderer h; 
String outputName = "sketchyExample.pdf"; 

void setup()
{
  size(400, 250, PDF, outputName);
  h = new HandyRenderer(this);
}

void draw()
{
  background(247, 230, 197);
  h.rect(width/4, height/4, width/2, height/2);

  noLoop();  
  println("Rendered sketch to "+outputName);
  exit(); // Necessary when using PDF output.
}
```

_edit:_  See my post below for a `beginRecord()` /  `endRecord()` example.

**Comment by Ohmarinus** [comment]
Thanks, your solution seems to work. The only downside to PDF export is that it crops the generated image and generates some unwanted geometry. Nothing I can't clean up by myself though. Now I'm going to figure out how to get rid of the double lines. I would like HandyRenderer to output single lines.  Thanks for your suggestion!

**Comment by jwoLondon** [comment]
Here's a working example that uses the the `beginRecord()` / `endRecord` approach. The key line that was probably missing in your original is `h.setGraphics` which is required to direct output from the handy renderer to PDF instead of screen.

This approach has the advantage that you can keep it integrated with the rest of your sketch without having to terminate it.

```java
import processing.pdf.*;
import org.gicentre.handy.*;

boolean record;
HandyRenderer h; 
PGraphics pdf;

void setup() 
{
  size(400, 400);
  h = new HandyRenderer(this);
  pdf = (PGraphicsPDF) createGraphics(width, height, PDF, "output.pdf");
}

void draw() 
{
  if (record) 
  {
    beginRecord(pdf);
    h.setGraphics(pdf);
  }

  background(247, 230, 197);
  h.rect(width/4, height/4, width/2, height/2);

  if (record) 
  {
    endRecord();
    h.setGraphics(g);
    record = false;
    println("PDF output created");
  }
}

void keyPressed() 
{
  if (key == 'p')
  {
    record = true;
  }
}
```

Could you give an example of the 'unwanted geometry'? As far as I can see, PDF output should be identical to what you would see with normal screen output.

**Comment by Ohmarinus** [comment]
I'm sorry, I meant the double lines were unwanted geometry.
Still searching :) I checked the documentation but couldn't find a setting to have the renderer create only one line. The reason why I want one scribbly line is because I am using this for vector output to generate pen plotter files.

![doubles](https://user-images.githubusercontent.com/5002107/104124065-e76a7400-534e-11eb-9756-6c11798f98ae.jpg)

**Comment by jwoLondon** [comment]
Thanks for the clarification. The double stroking is currently a fundamental part of the 'sketchy' design, but feel free to add a separate feature request issue and I will see if I can look into it.

Given your original query is now solved, I will close this issue.
